### ISSUE TITLE
plotDistToTSS: error when trying to plot multiple objects

### ISSUE THREAD

**Issue by massimofagg** [YuLab-SMU/ChIPseeker#149]
Hi, I am encountering an error when I try to plot at the same time all the 6 objects of a "PeakAnnoList" using plotDistToTSS, instead when plotting only an object at a time it works normally. Also plotAnnoBar works. Here it is the error: 

Error: Column 30 must not have names of the form ... or ..j.
Use .name_repair to specify repair.

Hope You could help.

**Comment by MingLi-929** [comment]
I think the error may come from your own file.
I try to use `plotDistToTSS()` to plot either one object or 5 objects(use the data from the CHIPseeker), it surely work.
```
library(ChIPseeker)
require(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(org.Hs.eg.db)

txdb = TxDb.Hsapiens.UCSC.hg19.knownGene
files=getSampleFiles()
peakAnno <- annotatePeak(files[[4]], 
                         tssRegion=c(-3000, 3000),
                         TxDb=txdb, annoDb="org.Hs.eg.db")
peakAnnoList <- lapply(files, annotatePeak, 
                       TxDb=txdb,tssRegion=c(-3000, 3000))
plotDistToTSS(peakAnno)
```
![1](https://user-images.githubusercontent.com/78794151/119630114-3669ff00-be41-11eb-8a48-ea6ddd3051cb.png)


```
plotDistToTSS(peakAnnoList)
```
![2](https://user-images.githubusercontent.com/78794151/119630154-41249400-be41-11eb-8e64-0fab17b9823a.png)

**Comment by AJqd** [comment]
Hi, I encounted the same error..

> plotDistToTSS(peakAnnoList)
Error in `as_tibble()`:
! Column 9 must not have names of the form ... or ..j.
Use `.name_repair` to specify repair.
Caused by error in `repaired_names()`:
! Names can't be of the form `...` or `..j`.
✖ These names are invalid:
  * "..1" at location 1.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/tibble_error_column_names_cannot_be_dot_dot>
Error in `as_tibble()`:
! Column 9 must not have names of the form ... or ..j.
Use `.name_repair` to specify repair.
Caused by error in `repaired_names()`:
! Names can't be of the form `...` or `..j`.
✖ These names are invalid:
  * "..1" at location 1.
---
Backtrace:
     ▆
  1. ├─ChIPseeker::plotDistToTSS(peakAnnoList)
  2. ├─ChIPseeker::plotDistToTSS(peakAnnoList)
  3. │ └─ChIPseeker:::plotDistToTSS.data.frame(...)
  4. │   └─... %>% mutate(freq = freq / sum(freq) * 100)
  5. ├─dplyr::mutate(., freq = freq/sum(freq) * 100)
  6. ├─dplyr::group_by(., .id)
  7. ├─dplyr::summarise(., freq = length(Feature))
  8. ├─dplyr::group_by(., .id, Feature, sign)
  9. └─dplyr:::group_by.data.frame(., .id, Feature, sign)
 10.   └─dplyr::grouped_df(groups$data, groups$group_names, .drop)
 11.     └─dplyr:::compute_groups(data, vars, drop = drop)
 12.       ├─tibble::as_tibble(data)
 13.       └─tibble:::as_tibble.data.frame(data)
 14.         └─tibble:::lst_to_tibble(unclass(x), .rows, .name_repair)
 15.           └─tibble:::set_repaired_names(...)
 16.             └─tibble:::repaired_names(...)
>

**Comment by AJqd** [comment]
Possible solution: Please check the presence of header of input files for annotatePeak (idr-bed file). The absent of header may cause the incorrect use of the first line of the Peak file to be the header. You can add the header manually according - https://github.com/nboley/idr?tab=readme-ov-file#output
